base: 'http://cms24.s2310456019.student.kwmhgb.at/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: DE
    flag: at
    hreflang: ''
    websiteTitle: ''
  -
    title: Englisch
    enabled: true
    locale: en_US
    hreflang: en-Us
    base: /en/
    websiteTitle: Farming
    navigationTitle: EN
    fallbackType: strict
    fallbacks: ''
    flag: us
    languageId: 1
rootPageId: 1
websiteTitle: Landwirtschaft
